appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: rQ2FYwc5uqiNjpYhrW4YLYADiwpgrwj2XH1aUuflG46HzO/iTeRgXMxNjpKZxBjqAWak1ILEoARf7eO0KkdngJCJBveF+knIy7wlA5rT4M9r5s6iLr+++3XwlO3cQcPZNsq8qeKqL0ky8yQhOzWXaJrS/fWcUyqROBehm8GSrQU6RV1KxayJ63XmWw2mYIqK39RwLmLW6q0fpv0+8Ed2OTkclD8MPTzMIDVF0iN9iM+W24879ThQoddsw80sZW+x/cR+093iTX+oDXsX5LKNZ/L4Hn1enRnna9XuMS6UixDfNf5U4nqtO2zle+fQDr02FKNrJZOuxTGk52UGBus5/59yX3t8YwpM59B1E6W/w1eyeM0SNT1AB7mW0XhnP+tW3G/Wcw7DbcS/au7XzbGEL7WXwsEOwMHCgs5OWbAfm9o19Sj4QZDXHGsz0HiA5bDlydIEwJ40+Ry4y/Rf/iQw6ASl8O7rQfOoOLUUe29HLfvUdKPV33r61xrKEiF/pdUUIXitv3qEA0rK/yMs+wPXYC8xX02b/YuJ8CD8lmPYm6H0Rtt4HV2DCpm0UBN4h2BS4V2+7Cw610g7gHnGiUesQBPxLnB8gGGE1llCb2MI9ZzmmngLCtQ2JvR4ZNBaBkjFq225/H/0sc5cOnax8ykWVqjrZrdfTldVC10GwPpOTLc=
